### PR TITLE
trigger-ci: merge from dev to main

### PR DESCRIPTION
**Pull request by timemeansalot**
update readme in dev branch

### CODE REVIEW

**Comment by timemeansalot** [comment]
trigger-ci_dev: trigger CI by comment manually

**Comment by tenyears-fu** [comment]
trigger-ci_dev: trigger CI by comment manually from another user

**Comment by timemeansalot** [comment]
trigger-ci_dev: test aws

**Comment by timemeansalot** [comment]
trigger-ci_dev: test aws after update github app permission

**Pull request merged**
